docs:
  - '**/*.md'
  - '**/*.MD'

.github:
  - '.github/**/*'

CI:
  - '.github/workflows/**/*'
  - '.github/actions/**/*'

go:
  - '**/*.go'

tests:
  - '**/*_test.go'
  - '**/testdata/**/*'
  - 'test/**/*'
  - '.golangci.yml'
  - 'codecov.yml'
  - '.codecov.yml'

docker:
  - 'Dockerfile'
  - '.dockerignore'

dev:
  - 'Makefile'
  - 'docker-compose.yml'
  - '.gitignore'
  - '.editorconfig'
